### ISSUE TITLE
API 3.0.0ALPHA7 

### ISSUE THREAD

**Issue by teracube** [jasonwynn10/Other-Plugins#1]
Hi,

possible to upgrade compatibility API 3.0.0ALPHA7  ?
thanks very much

**Comment by jasonwynn10** [comment]
which plugins would you like updated?

**Comment by teracube** [comment]
Hi,

LostPets and FakeAdmin if possible
thanks

**Comment by jasonwynn10** [comment]
Neither of those ever worked

**Comment by teracube** [comment]
ok thanks

and possible to upgrade  NameTagMods on Alpha 7 ?
